language: bash
services: docker

env:
  - VERSION=7.2 VARIANT=PHP-FPM

before_script:
  - env | sort
  - cd "${VERSION}"

script:
  - travis_retry docker build -t test_image .
  - docker run -d -p 127.0.0.1:80:80 --name test_container test_image
  - docker ps | grep -q test_container